# Generated by Django 3.1 on 2020-08-28 15:50

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('decription', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('document', models.FileField(upload_to='notes/')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.ManyToManyField(to='notes.Tag')),
            ],
        ),
    ]
